In [119]:
import numpy as np

In [120]:
list1 = [3,4,5]
print(list1)

[3, 4, 5]


In [121]:
arr = np.arange(1000)

In [122]:
pylist = list(range(1000000))

In [123]:
%time for i in range(10): [item*3 for item in pylist]

CPU times: user 770 ms, sys: 235 ms, total: 1.01 s
Wall time: 1.06 s


In [124]:
%time for i in range(10): arr = arr*3

CPU times: user 67 µs, sys: 10 µs, total: 77 µs
Wall time: 82 µs


In [125]:
np.array([2,3,1,45,7])

array([ 2,  3,  1, 45,  7])

# Numpy Functions

In [126]:
array = np.array([2,3,1,45,7])
print(type(array))

<class 'numpy.ndarray'>


In [127]:
array1 = np.array([[1,3,5.0,7],[2,3,5,6]], dtype = 'int32')
array1

array([[1, 3, 5, 7],
       [2, 3, 5, 6]], dtype=int32)

In [128]:
 array1.shape

(2, 4)

In [129]:
array1.dtype

dtype('int32')

In [130]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [131]:
np.ones(4).dtype

dtype('float64')

In [132]:
np.empty((6,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [133]:
array1*array1

array([[ 1,  9, 25, 49],
       [ 4,  9, 25, 36]], dtype=int32)

In [134]:
array1+array1

array([[ 2,  6, 10, 14],
       [ 4,  6, 10, 12]], dtype=int32)

In [135]:
array1/array1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [136]:
1/array1


array([[1.        , 0.33333333, 0.2       , 0.14285714],
       [0.5       , 0.33333333, 0.2       , 0.16666667]])

# Slicing

In [137]:
array2 = np.array([5,4,56,63,6,6,6])

In [138]:
arr = array2[4:6]

In [139]:
arr

array([6, 6])

In [140]:
arr[0] = 9

In [141]:
arr1 = array2[4:6].copy()

In [142]:
array2

array([ 5,  4, 56, 63,  9,  6,  6])

In [143]:
arr1[0] = 9

In [144]:
array2

array([ 5,  4, 56, 63,  9,  6,  6])

# More Functions

In [145]:
import numpy as np

In [146]:
a = np.array([[1,2,4],[3,5,7]])

In [147]:
a.sum(axis=0)

array([ 4,  7, 11])

In [148]:
a.sum(axis=1)

array([ 7, 15])

In [149]:
b = np.array([[3,6,9],[3,5,0]])

In [150]:
b.transpose()

array([[3, 3],
       [6, 5],
       [9, 0]])

In [151]:
a.dot(b.transpose())

array([[ 51,  13],
       [102,  34]])

In [152]:
np.dot(a,b.transpose())

array([[ 51,  13],
       [102,  34]])

In [153]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [154]:
np.cross(a,b)

array([[ -6,   3,   0],
       [-35,  21,   0]])

In [155]:
c = np.array([[21,6,90],[3,51,0]])

In [156]:
np.sort(c)

array([[ 6, 21, 90],
       [ 0,  3, 51]])

In [157]:
np.sort(c, axis = 0)

array([[ 3,  6,  0],
       [21, 51, 90]])

In [158]:
np.sort(c, axis=0, kind = 'mrege sort')

array([[ 3,  6,  0],
       [21, 51, 90]])

## Other functions

In [159]:
import numpy as np

In [160]:
d = np.arange(6)

In [161]:
d

array([0, 1, 2, 3, 4, 5])

In [162]:
c = np.array([1,3,5,7,23,4,5,66,78,45,4,1,10,89,3,24])
c.shape

(16,)

In [163]:
# c = c.reshape(4,4)

In [165]:
c

array([ 1,  3,  5,  7, 23,  4,  5, 66, 78, 45,  4,  1, 10, 89,  3, 24])

In [166]:
np.argsort(c)

array([ 0, 11,  1, 14,  5, 10,  2,  6,  3, 12,  4, 15,  9,  7,  8, 13])

In [169]:
np.argmin(c)

0

In [170]:
np.argmax(c)

13